### PR TITLE
add python package fdasrsf

### PR DESCRIPTION
**Pull request by jdtuck**

### CODE REVIEW

**Comment by jdtuck** [comment]
#2

**Comment by fabian-s** [comment]
playing a dangerous game, here @jdtuck -- not sure how pluralistic R task view head honchos are re. Python.
jk..  i'd say let's merge this?

**Comment by jdtuck** [comment]
I think so, we mention other software at the bottom, was completing the list.

**Comment by jdtuck** [comment]
Also sorry this slipped through my notifications and should have responded sooner

**Comment by fabian-s** [comment]
no worries, none of this is urgent ;)

**Pull request merged**
